CACHE MANIFEST

# Build <?php echo date('l jS \of F Y h:i A'); ?>

CACHE:

 
./index.php
./css/bootstrap.min.css
./css/font-awesome.min.css
./plugins/animate/animate.css
./plugins/creative-brands/creative-brands.css
./plugins/vertical-carousel/vertical-carousel.css
./css/custom.css
./css/bootstrap-glyphicons.css 
./css/menu3d_libre.css
./css/hover-min.css
./css/mcvela_css.php
./css/timeline.css
./font-awesome/css/font-awesome.min.tree.css
./js/jquery-1.11.0.min.js
./build/three.min.js
./js/controls/OrbitControls.js
./js/Mirror.js
./js/WaterShader.js
./js/Detector.js
./js/libs/stats.min.js
./js/bootstrap.min.js
./js/jquery.magnific-popup.min.js
./plugins/creative-brands/creative-brands.js
./plugins/easy-pie-chart/jquery.easy-pie-chart.js
./plugins/modernizr/modernizr.custom.js
./plugins/waypoints/waypoints.min.js
./js/custom.js
 
./textures/waternormals.jpg
./textures/madrid2.jpg 
./img/mcvela_profile.jpg
./img/profile.jpg
./image/vctaskforce.png
./image/rocketspace.png
./image/abc.png
./image/modet.png
./image/leroymerlin.png
./image/envision.png
./image/envision2.png
./image/carrefour.png
./image/lico.png
./image/telefonica.png
./image/wunderman.png
./image/wunderman2.png
./image/frogtongvideo1.png
./image/frogtongvideo2.png
./image/mba.png
./image/iede.png
./image/eresmas.png
./image/eresmas1.png
./image/muchomedia.png
./image/laaventura.png
./image/laaventura2.png
./image/internationalmobius.png
./image/newsintermobius.png
./image/barcelonamobius.png
./image/elprincipefeliz.png
./image/principe_taller.png
./image/ucm.png
./image/rockford0.png
./image/rockford.png
./image/explorama2.png
./image/explorama.png
./image/grupoanaya.png
./image/anaya2.png
./image/amaseguros.png
./image/laburator.png
./image/matchbook.png
./image/wunderman_ini.png
./image/allfundsbank.png
./image/atsistemas.png
./image/xanadu.png
./image/ticjob.png
./image/video-ticjob.png
./image/download_github.jpg
./image/maavbrain.png
./fonts/SL0aFUFfkFMMdariYQ3_YY4P5ICox8Kq3LLUNMylGO4.woff2
./fonts/Q94aHXFHGip10K5uxi1jOFtXRa8TVwTICgirnJhmVJw.woff2
./fonts/HGfsyCL5WASpHOFnouG-RFtXRa8TVwTICgirnJhmVJw.woff2
./fonts/6kgb6ZvOagoVIRZyl8XV-DUAV8re_zuY5FPJtiiylrU.woff2
./fonts/zhcz-_WihjSQC0oHJ9TCYPk_vArhqVIZ0nv9q090hN8.woff2
./fonts/aZltdVk5hwkm2fox1xEVyyEAvth_LlrfE80CYdSH47w.woff2
./fonts/4FUUC-PxqHfbmE-DcA6LXCEAvth_LlrfE80CYdSH47w.woff2
./fonts/GtRkRNTnri0g82CjKnEB0Q.woff2
./fonts/EsvMC5un3kjyUhB9ZEPPwg.woff2
./fonts/1YwB1sO8YE1Lyjf12WNiUA.woff2
./fonts/H2DMvhDLycM56KNuAtbJYA.woff2
./fonts/tI4j516nok_GrVf4dhunkg.woff2
./fonts/9TBVFLzQ3GUZLG8FZ4yrEfesZW2xOQ-xsNqO47m55DA.woff2
./fonts/2HG_tEPiQ4Z6795cGfdivFtXRa8TVwTICgirnJhmVJw.woff2
./fonts/PLygLKRVCQnA5fhu3qk5fQ.woff2
./fonts/HkF_qI1x_noxlxhrhMQYEFtXRa8TVwTICgirnJhmVJw.woff2
./fonts/VNUH7ZAcagYBWsAiBBCEY1tXRa8TVwTICgirnJhmVJw.woff2
./fonts/EsvMC5un3kjyUhB9ZEPPwg.woff2 

./fonts/fontawesome-webfont.ttf?v=4.0.3
./fonts/fontawesome-webfont.svg?v=4.0.3
./css/allfonts.css
./image/macbook_big.png
./image/offline.png
./js/jquery-latest.min.js 
./js/bootstrap.min.js
./js/jquery.magnific-popup.min.js
./plugins/creative-brands/creative-brands.js
./plugins/easy-pie-chart/jquery.easy-pie-chart.js
./plugins/modernizr/modernizr.custom.js
./plugins/waypoints/waypoints.min.js
./js/custom.js
./fonts/fontawesome-webfont.woff 
./img/background/1.jpg 
./img/background/2.jpg 
./img/background/3.jpg 
./img/background/4.jpg 
./img/background/5.jpg 
./img/background/6.jpg 
./img/background/7.jpg 
./index.php?m=study#about
./index.php?m=work#about
./index.php?m=award#about
./image/staticmap.png
./js/analytics.js
./js/imagesloaded_pkgd_min.js
./textures/madrid0.jpg
./textures/madrid1.jpg
./textures/madrid2.jpg


NETWORK:
http://*
https://*